### ISSUE TITLE
Aragon Nest Proposal: "Minecraft" worlds as DAOs, with real-value blocks/mobs/items

### ISSUE THREAD

**Issue by danimesq** [aragon/nest#125]
# Aragon Nest Proposal: "Minecraft" worlds as DAOs, with real-value blocks

## Abstract

Something in common for [Aragon](https://aragon.org/), [Enjin](https://enjincoin.io/), [Decentraland](https://decentraland.org/) and [Minetest](http://www.minetest.net).

If we follow the vision of [Enjin](https://enjincoin.io/), all game assets should have real ownership, and value;
If we follow the vision of [Decentraland](https://decentraland.org/), all virtual properties should have registered ownership and real value;
If we follow the vision of [Aragon](https://aragon.org/), virtual organizations are viably and securely democratic;
If we follow the vision of [Minetest](http://www.minetest.net), Minecraft should be totally free and open-source.

Why not bring all those amazing visions into the same project? This is the purpose of this proposal: all [Minetest](http://www.minetest.net) blocks (and mobs/items) with value and being assets on [Enjin](https://enjincoin.io/), and worlds being [Decentraland](https://decentraland.org/)'s properties and [Aragon](https://aragon.org/)'s DAOs (not exactly like an usual Aragon DAO).

It will not need partnership with Enjin/Decentraland but only the use of their platforms. About Minetest and Aragon's funded team, they probably will need some cooperation on making a real-value Minetest; unless an Minetest plugin could achieve all of that described on this proposal.

One of the utilities regarding Aragon's DAOs on Minetest, is that they can have their own "physical" installations for conferences, while keeping its virtual form.

If you told about Bitcoin and that it haves mining, a Minecraft user should imagine he using a pickaxe for mining gold ores and creating Bitcoin after forging gold;
If you told about CryptoKitties for a Minecraft user, he could ask if that is a plugin for bringing cute cat mobs for Minecraft; but if instead of mining with hardware, he could really mine with its pickaxe? and instead of selling Bitcoin, he could sell his ores, blocks, seeds, animals and other items?

I believe on the open, entertaining, educative and free power of Minetest.

**Note: I don't have skills to make it working, but to propose it; then you're free to begin implementing it on a pull request and receive your grants.**

## Deliverables

- [ ] Minecoin, as main in-game coin to store value as fungible coins
- [ ] Use IPFS for serving Minetest servers instead of centralized servers
- [ ] Use an identity provider for decentralized unique usernames, using [Civic](https://www.civic.com/)
- [ ] API where Minetest's plugins can use blockchain for their blocks/mobs/animals
- [ ] Smart contract(s) for the [ERC1155](https://bitcoinmagazine.com/articles/enjin-coin-cto-creates-erc-1155-new-token-standard-ethereum/)-compatible token(s).
- [ ] Public network statistics (where users can see if other users are cheating)

----

- [ ] Hardware worker uses PoW to generate Minetest blocks to compose a "Minecraft" world
- [ ] PoW difficulty is adjusted by blocks/animals/mobs value, in a manner that hardware worker haves electrical costs covered (based on the fact that he earns 1/3 from mined blocks)
- [ ] Every kind of block and animal/mob is an individual token with its own value
- [ ] Hardware worker can set the form and size of the world by using a seed, which can require less or more work on PoW; there will be a minimum size for worlds to support a maximum of 12.000 users, and they can support more users than that if they are bigger than the minimum size
- [ ] The minimum user amount for an world is 5% of its maximum (for example, 600 users is the 5% minimum of 12.000 maximum, and an world is only valid if it receives its minimum members - they doesn't needs to be online, but just join the network as brand new and verified users)
- [ ] Minimum amount of kind of block to be generated by hardware worker, to generate an valid world with enough resources
- [ ] Hardware workers can't mine their own generated blocks and mobs/animals
- [ ] Hardware workers can't be member of their own generated world
- [ ] When generating a world, it will be both an DAO and an Decentraland's land/property, and its ownership will be given for brand new users that doesn't haves a world yet
- [ ] User can only earn an world if verified through [Civic](https://www.civic.com/)
- [ ] Users joins this world, earns some Minecoins (on a chest with his name and basic items/food) and starts mining
- [ ] An world divides onto chunks to be seeded by users (uses IPFS)
- [ ] Hardware worker earns one block for every two blocks mined (the third mined block of the same type, is for the hardware worker) and these blocks will be transferred to his Ethereum wallet and can appear on his inventory on Minetest
- [ ] Hardware worker earns one living mob/animal for every two (generic) animals of the same specie that are killed/caught
- [ ] Putting blocks towards an animal/mob catches it for your Ethereum address (like mining)
- [ ] When an world haves the last two kind of block or mob/animal, the hardware worker earns one of them (when block is mined or mob/animal is killed/caught)
- [ ] When mining with the wrong tool, user can't cheat to say it is the right, because the network registers what was the tool used and if it is on user's ETH address
- [ ] Members of an world or house haves voting weight according to their contributions; for example, he/she builds some roads and asks if members likes it
- [ ] If mining/constructing too quickly, user receives a captcha before doing it again
- [ ] If user is using bot, the whole blockchain bans he/she for some days, and it is increased if user repeats that; the blockchain is an DAO and only contributors are members; user can report another user, and the blockchain DAO votes about that
- [ ] User can buy or sell blocks/animals/mobs with Minecoins
- [ ] User can exchange blocks/animals/mobs for Minecoins (it is not like selling - when exchanging, the blocks are burnt and animals/mobs killed - the animals/mobs with DNA can't be exchanged)
- [ ] Unlike generic mobs/animals, there will be unique mobs/animals with their own DNA characteristics, that will be minted by blockchain on worlds every 6 months
- [ ] Monster mobs can be caught and used on PvP battles
- [ ] Blocks and generic mobs/animals are fungible collectibles, while mobs/animals with DNA are non-fungible; those can be transferred, sold or bought
- [ ] With some ETH gas, user's mobs/animals can mint new ones with their DNA (or no DNA if they are generic)
- [ ] Wild mobs/animals can mint children without fees
- [ ] Users can visit other worlds (even when banned, he can see how users are building/mining, to keep the network secure), but can't build/mine if isn't member
- [ ] When visiting other world, user can be proposed as member, and voted; if approved by both sides (voters and the user), he isn't anymore member of the previous world
- [ ] Even not being anymore an member, user keeps its vote weight value, but when banned this weight is reduced
- [ ] Worlds haves portals on each side, that links to other worlds (forming a map on network)
- [ ] World's portals are connected by similar sides (seas to seas, lands to lands)
- [ ] Seeds to generate ocean worlds; those special worlds needs to be 15x bigger than the minimum size, and have islands that together haves the same minimum size of an world (islands needs to have the biggest possible distance between them)
- [ ] When joining, members of ocean worlds earns lots of Minecoins because of their difficulties; they spawn on their own island
- [ ] There is a 95% chance of an ocean world side being connected to another ocean world
- [ ] Rockets, with which users can visit other worlds by their shareable link
- [ ] Three kinds of DAOs: Aragon's originals (came from Aragon and bought a territory on an world), an Minetest world (where users can be member of just one world), and an user's house
- [ ] "DAOs inside DAOs": an DAO can buy a part of territory on an world
- [ ] User can buy part of territory to construct an house; its unlimited and each house became an DAO
- [ ] Both Aragon's original DAOs and users can buy territories even if they aren't member of an world
- [ ] Buying territories depends on world member's votes, and the Minecoin amount is divide between the members that did positive vote
- [ ] World members can't set the value of territories, because it is metered from blocks (land horizontal blocks and all blocks that are bellow - because they will be mineable)
- [ ] On houses (as this is a different kind of DAO), any action depends on voting
- [ ] Members of an house can vote to ban another member; the construction value divides between them and the banned user takes it on blocks and can't visit this territory again
- [ ] Even the most weighted voters of an world doesn't haves permissions over Aragon's and houses's DAOs (sold territories)
- [ ] Members of sold territories can sell them for any value
- [ ] World members can vote to ban another member; when banned, he can be member of other worlds when visiting them, in the case it is proposed
- [ ] Inactive members are banned after one month (not from blockchain), so the votes on an world doesn't anymore relies on offline users

I suggest the granted team to use part of the grants to begin an ICO (with airdrop and bounty if needed), for having more resources for completing this complex but amazing task. This ICO would be very innovative (as the first interactive ICO), if gives option to buy Minetest blocks and animals/mobs to add to basket.

## Grant size

Funding: Up to $150k in ETH, split into chunks paid out over achieved deliverables.

Success reward: Up to $100k in ANT, given out when all deliverables are ready.

## Application requirements

- Proof of concept of the smart contracts for the [ERC1155](https://bitcoinmagazine.com/articles/enjin-coin-cto-creates-erc-1155-new-token-standard-ethereum/)-compatible token. Alternatively, a whitepaper researching the implementation of the whole protocol
- Details of the team members, alongside with their willingness in terms of implication
- Estimated average burn rate for completing the deliverables
- Legal structure to be adopted, if any

## Development timeline

To be discussed or to be proposed by the team requesting funds.

**Comment by DaniellMesquita** [comment]
I ask what Minetest team thinks about that unbelievable thing:

@Calinou @celeron55 @Ekdohibs @Ezhh @kahrl @nerzhul @paramat @rubenwardy @sapier @sfan5 @ShadowNinja @SmallJoker

**Comment by StephenLynx** [comment]
Mano, sua idéia é retardada pra caralho. vlwflw

**Comment by StephenLynx** [comment]
Gostaria de apontar que ethereum perdeu 80% do seu valor nos últimos 12 meses e continua caindo. Você vai tirar ethereum de onde pra cobrir os 150k USD na hora de pagar?

**Comment by StephenLynx** [comment]
Você falar que vai pagar em ethereum é o mesmo que falar que vai pagar com porra de unicórnio.

**Comment by DaniellMesquita** [comment]
This comment is to explain the purpose of this proposal and to map about this intentional conflict made by @rubenwardy and his colleagues. The quotes are for the words that aren't very relevant for a quick lecture.

**Clarifying all that for Minetest's honest members, this proposal isn't intended to transform Minetest into a blockchain-obligatory game, where you need to pay fees for every mining and/or see captchas that pauses the character's movements; that is just an alternative mode for giving untamperable common structure, a new dimension to physics (by their generation) and real value to an voxel building game; and plays that only who wants to, and the other users can keep playing on survival/creative/multiplayer normal modes. Like on Bitcoin's initial times, only the ones with mental confusion and blind mind could not see its good potential. Same for Ethereum on 2014 and other following projects.**

> The first signal of the death of Aragon (as ICOs are coming to purpose-death when only private investors are welcome) is when a reviewer says: "I'm not with fear from they, they're just immature gamers, but tbh your proposals about Open Badges and Minetest can't be accepted for bla bla bla". When with fear about hearing me, it is just being against the project's Manifesto. To have fear, you need to have courage: to face that you are contributing not only to the enemy of others, but to your indirect enemy; the threat against a good one is an treat against a good all.
> I know this story: who is against (affiliated with influential groups) will laugh against (like seem on the above comments), while this project's reviewers will reply against me like puppets; the world doesn't changes (probably it isn't intended to do so). Unless Aragon's team are free fearless people thinking on common good above everything.

I'm writing a kind of a more paranoid and psychologically-oriented Manifesto about how I see Aragon, other projects and the current word-wide governing system. I write from a Latin country (Brazil) that is with an retrograde and oppressive government, while we live on poverty but keeps studying outside the government's educational systems (that are very retrograde and doesn't incentives its users - because of that I'd suggested an educational platform for Aragon as of #123 ).

When you are retrograde, you are stepping back to the moment of your birth, which means death.
The world and his nature are getting bad every time, while suicidal (but powerful and influential) mans just thinks about eating and earning money against anything (which includes the life around). And they can't see any other different thing, so they will be against.

Wrong? You don't need to be from Avaaz to know that big corporations destroys the nature without care, being mentally blind by money; they care about their childrens? they care about their grandsons and the following generations?
`- "but there are better people on power, they doesn't shares the same thoughts"`
Liar! Those big corporations exists since the begin of this system, and keeps existing, because they gives lots, and lots of money amounts to the governments. Public workers (from public institutions from governments) mostly haves a family and need to bring sustain to them; and lies and does things as their governments please. Discreet groups are inside governments and big corporations to ensure they are working, big corporations (and private investors) sustain the governments and the governments as well sustain them with favors. Courts are paid and laws are interpreted and hiddenly-changed as the strong side please.

As I've wrote on my reports, they born with existential crisis and hates everything, but tries to hide it; they smiles, says beauty words full of moralism or discourses with hidden hate, doesn't see the flavors of life but wants to take most of things to them (like bad kids that says "if it can't be mine, can't be yours, ok, I don't like those candies, but I'll take everything and smile"); **because of that the poverty, inequality and hidden slavery yet exists.** Who is against, is called "bad", "not useful" and "bum". If the owners of the world can't be happy, no one can (except their ally psychopaths with fake smile, or their slaves that smiles with sadness but are a very little happy with the poor things they have).

**This is where Computing, Internet, Open-Source, BitTorrent, Bitcoin, Ethereum, Civic and Aragon came to help.** No, these technologies aren't made by freem***** (they will want to say so, because they takes credit for building everything they destruct) or anything affiliated/endorsed to governments/societies/groups, but by independent real free-thinker developers around the world that aren't separated from the normal society/common-good by alternative societies, religions, sects, secret/discrete groups or jobs. Yes, society is bad, but because the manipulation exists and the education lacks; society is naturally good and their word is mandatory. Tor was created by an government (and because of that it is provably vulnerable), and a independent developer solved that by creating i2P (that is distributed, and not centralized on servers like Tor does). Remember the ants: they aren't slaves from their colony, and works on what they likes to since their birth, without creating any secret/discreet alternative society.

**Comment by StephenLynx** [comment]
Take your head out of your ass, this is not a conspiracy against you. People are just saying your idea is bad.

**Comment by StephenLynx** [comment]
And here's how it works that all kinds of people come to make fun of you and do reactions on posts. Someone read this, think it's funny and post on discord. Then someone elses see, think it's funny too and posts on some random irc channel. Someone sees that and tweet it. And so on.

**Comment by DaniellMesquita** [comment]
@StephenLynx 
> Mano, sua idéia é retardada pra caralho. vlwflw

> Gostaria de apontar que ethereum perdeu 80% do seu valor nos últimos 12 meses e continua caindo. Você vai tirar ethereum de onde pra cobrir os 150k USD na hora de pagar?

> Você falar que vai pagar em ethereum é o mesmo que falar que vai pagar com porra de unicórnio.

Like I've said, those mans (like you) haves beauty words full of moralism, at same time they reverberate their hate.
Your argument, as usual from an high-power psychopath (and also from a low-power, due to the bad-words used), uses tricky math to lie and explain why to be against a good thing.

Translating your intentional 3 comments (commented with 11 minutes of difference between them, like your new two comments) into one comment:

> Brow, your idea is fucking retarded. thxbye
> I like to point that ethereum lose 80% of its value on the last 12 months and keeps falling.
> You will retrieve ethereum from where to cover the 150k USD when paying?
> You talk that will pay in ethereum is the same of speaking that will pay with fucking unicorn.

Well, this group I know on Brazil (they are installed on the whole world, and didn't came from Brazil) likes too much to say "brow" (mano), "thxbye" (vlwflw) and to attack who likes unicorns. Other things about that I've already said above regarding your comments (uses tricky math to lie and explain why to be against a good thing).

I'll also paste your new comment, because they are all basically the same roar from your hate and can be properly (without faults) replied on a single paragraph.

> Brow, your idea is fucking retarded. thxbye
> I like to point that ethereum lose 80% of its value on the last 12 months and keeps falling.
> You will retrieve ethereum from where to cover the 150k USD when paying?
> You talk that will pay in ethereum is the same of speaking that will pay with fucking unicorn.
> Take your head out of your ass, this is not a conspiracy against you. People are just saying your idea is bad.

First, you said that the idea is retarded (just because you need to say that, you feel yourself less bad when depreciating things) and tried to do an "turn down for what" to close the discussion with you being right and your depreciated things wrong. After 11 minutes you returned (after searching about Ethereum, what you pronounce with lowercase; and search if it is falling, to use it to say the idea is not viable) and used your search to explain that Ethereum haves no value to be used to fund this proposal; because you also want Minecraft/Minetest to have no value; while your children/youth freely plays Minecraft, the others you all says that are "bums" (because those voxel games doesn't haves real value).
You seem to be fixated about the "idea" word (typical from an "psycho"), but do you really haves ideas or you just knows how to destruct instead of construct? No need to answer: psychopaths hates the "good", "dream", "idea" and other words that represents good things. Ideas are only for constructive things, and you clearly haves envy about other people having ideas, and also about who knows English (as you initially commented three times on Portuguese, and probably used Google's Translator to comment again). My idea is retarded but you're not retarded? You've ignored lots of comments for then realizing only English is used on this issue and mainly used on GitHub.

An there is no People saying those specs are bad, but a minority of shills. Regarding conspiracy, you just confirm the group you is part, because they likes to reply that who discovers them are just saying conspiracy theories. The president of an country (Kennedy) discoursed a lot against secret/discreet groups, and when killed, the murderers were against the true theories (discoveries about the murder) calling'em "conspiracy theories".

Well, I also ask you (as of your words) to "take your head out of your ass" to see that the crypto market on 2018 were a bear market, based on the value of Bitcoin; so your data based on 12 months isn't to be considered as a fall of Ethereum, but from Bitcoin and the whole crypto market. On contrary of what you say, this is a month of a recovery not only for Ethereum, but for the whole crypto market; who knows how to discern from news can know that (and not fake news promoters like you).

Also, despite the value of Ethereum, please use an argument to explain why this proposal is bad; fair users will say what are the problems of an implementation and how to honestly fix or improve them, but persons like you just wants to destroy and hate. The major problem is that you're not sincere to your psychiatric ("I'm a happy man, no no I'm normal hehe, I'm from the moral and good will, everything normal the problem are those bums"), in the case you were humble to find one.

> And here's how it works that all kinds of people come to make fun of you and do reactions on posts. 

GitHub is not a place to make "fun" (what you call "fun" is just a form of hate) with destructive behavior, but by discussing/coding with coherent/cohesive/plausible arguments with constructive behavior/intention.
As I've said, for immature gamers the only good features of GitHub are the image posting and sticker/figure reactions; and that is an destructive and pseudo-rational act.

> Someone read this, think it's funny and post on discord. Then someone elses see, think it's funny too and posts on some random irc channel. Someone sees that and tweet it. And so on.

"elses"? I really doubt this issue were shared on many different social media; it doesn't makes sense. Also, too much coincidence that the first to write is a brazillian, because I didn't mentioned brazillians here. As I'm also brazillian, mass surveillance made you come here. Another thing: when for good things, there are no sharing, but when is to attack, there are lots of shares: that is an effect of censorship and data control.
We can only ask you to find a psychiatric and be sincere; but I know you don't want, because you're mentally blind.

**Comment by StephenLynx** [comment]
For someone who can't write english, you sure like to make long posts.

**Comment by DaniellMesquita** [comment]
That's the most common behavior:

![image](https://user-images.githubusercontent.com/6765277/50729941-c05a8580-1129-11e9-8977-99bbbd8d85e0.png)

Typical from an "psycho": after trying to trick with arguments that are intentionally placed to lie, haves a proper reply and then their hate grows and says: "long text, not useful, I'm right, I'll not read".
Also, you've replied too quickly about I've told you doesn't knows English. You're proving the surveillance, as a brazillian that haves tech knowledge for spying another brazillian.

**Comment by StephenLynx** [comment]
>You're proving the surveillance, as a brazillian that haves tech knowledge for spying another brazillian.
Ever heard of thunderbird desktop notifications?

**Comment by StephenLynx** [comment]
And by the way, the crypto market isn't just a bear market. It was a speculative bubble that burst, simple as that. There was absolutely NOTHING backing it up, it was just people trying to make a quick buck buying any memecoin and hoping they weren't the sucker holding the bags in the end.

**Comment by StephenLynx** [comment]
And since you are not going to do more than a reaction, let me ask you something: who cares if the whole market crashed and ethereum isn't any more worthless than any other cryptocoin? You are still promising something that is worthless. If ethereum is that good, why don't you trade it for real money and use this money instead?

**Comment by DaniellMesquita** [comment]
@StephenLynx

> Ever heard of thunderbird desktop notifications?

Normal people would say "well, thats because of" instead of "EVER HEARD": your words shows hate.
Even with a quick click on a notification, your answer was too quick for a long reading. And regarding the other things on the comment? You seem to, more than using good arguments, attacking good things and rebating "conspiracy theories", as this is the only part of the comment you wanted to reply.
I need to again ask you to find a psychiatric, as you doesn't admit when you're wrong and need to reply by last.

> And by the way, the crypto market isn't just a bear market. It was a speculative bubble that burst, simple as that. There was absolutely NOTHING backing it up, it was just people trying to make a quick buck buying any memecoin and hoping they weren't the sucker holding the bags in the end.

Well, [your] group likes to call other as "bums", but as I'm not like you, I'll not be kidding with your comments because thats not my work: I'm not a psychiatric, but go for one for you.
We can't discuss with persons that says crypto market is a bubble or gambling: as Felipe Neto says, that's like trying to talk with a goat.
When saying "simple as that" (as the cryptocurrency market isn't simple), you're speaking like Brazil's Bolsonaro when he says "all those things" as referencing what he doesn't understands.
People that tries to discuss with an ignorant, are ignorant; so I'll not explain why the crypto market doesn't just involves "memecoin" as Dogecoin and Ethereum Classic/Bitcoin Cash/Ethereum CV/Bitcoin Cash SV. The cryptocurrencies universe will show its purpose without needing that.

**Comment by DaniellMesquita** [comment]
@StephenLynx

> And since you are not going to do more than a reaction

How do you know I was tipping that I wouldn't reply you?

> MUH ILLUMINATI

No, Illuminati doesn't exist; that is a form of hidden that discreet "philosophical" group of "all rich mans".

> MUH BOLSONARO

He is an good person when compared to that group.

> Because I didn't read.
> For someone who can't write english [...]

Contradiction.

> MUH HATE

Self-explaining.

> let me ask you something: who cares if the whole market crashed and ethereum isn't any more worthless than any other cryptocoin? You are still promising something that is worthless. If ethereum is that good, why don't you trade it for real money and use this money instead?

For the same reason you don't trade all your physical money for credit card.

I really can't discuss with a person like you. You're so fixated after invading this issue, because lots of minutes after replying, you replied again without a new reply from me. I didn't searched for you, but you found me and is obsessed. Go find a good work (no need to registry or hard labor, just instead of being depreciative, be constructive).

**Comment by StephenLynx** [comment]
>I really can't discuss with a person like you.

Then don't. 

>you found me and is obsessed.

You are no more special than any other lolcow I mocked before.

**Comment by DaniellMesquita** [comment]
@StephenLynx 

> You are no more special than any other lolcow I mocked before.
You're not acting like if it is true.

> Then don't.

You keep wanting to reply by last, and the lolcow is me.

**Comment by StephenLynx** [comment]
If I am the one that keep wanting to have the last word, why do you keep replying then?

**Comment by DaniellMesquita** [comment]
@StephenLynx
> If I am the one that keep wanting to have the last word, why do you keep replying then?

You're so mentally blind that you can't see when you're wrong.
You are lying with what you could call "opinion", with no plausible arguments and ignoring things you can't answer; you just need to hate and attack to say you're living.

I'm not fond of figurative examples on that cases (for example of who says that an triangle is "perfect" and the world's power should follow it), but try to create an app: if you lie when writing, there will be bugs. Unlike what you and that group thinks, there is no relativity about the reason.
When someone keeps replying to your "arguments", that is like an browser console that is showing the bugs. If the app keeps sending bugged code, the browser keeps reporting that and replying about what is wrong. Again, I need to ask you to find an work (instead of the hobby of invading and attacking for "fun", that is worst than playing games - while unfairly the gamers are who are called "bums") and a psychiatric.

**Comment by DaniellMesquita** [comment]
@stellarmagnet

> Hey hey all...
> 
> Maybe it's time to take a deep breath?
> 

Thanks for your kind and peaceful comment. Machist mans can't discuss with a girl without flerting or depreciating, so I ask sorry if someone ignored you here; but we can't see mens/womens, but people.

> I am no authority on the Nest program, but from what I have observed, this doesn't seem like a proposal that would be approved.
> 

Yes, that is suposed, as I've said on a previous comment.
If it isn't approved, that will be really nonsense and a signal that Aragon is getting weaker, with fear about corporations (like MS, owner of both GitHub and Minecraft) and governments; because as DAOs are integrated on district0x and Decentraland, they couldn't be on "Minecraft"? As the open governance and open economy of Aragon, that shouldn't be applied to Minetest?

> I recommend trying to just calm down and wait for a response before getting too invested mentally and emotionally on this.
> 

I agree. But I'm just doing my part on trying to conscientize and psychopath and for a untamperable, cooperative and real-value voxel game.

> Lastly, I'm not sure this type of back & forth would be helpful for the approval.

Already replied above.

**Comment by StephenLynx** [comment]
![wut](https://i.kym-cdn.com/photos/images/newsfeed/000/000/151/n725075089_288918_2774.jpg)

**Comment by StephenLynx** [comment]
Also, could you talk more about this "group" I am part of?

**Comment by sofar** [comment]
@DaniellMesquita 

I've written in the past on merit vs. respect. Everyone should get respect. Everyone needs to earn merit. You self-handed destroyed any respect you had in this thread, and you have zero merit to begin with. Ultimately, you'll have to work really hard to get some merit and get any respect back, and this is your loss, but it is also your job.

Until then, your idea is sunk, entirely, by your own undoing.

![](https://i.redd.it/rwknyu50jmw11.png)

**Comment by paramat** [comment]
I have no interest in this.

**Comment by Bradymck** [comment]
@DaniellMesquita As a simple MVP, I think this could be tried in Minecraft now. Even though open source alternatives would be ideal, sometimes you have to bite the bullet to prove your point and convince people of your idea. 

For a model on how to do an MVP even without the knowledge to build all this yourself, take a look at Bitquest: http://bitquest.co/

While I agree an open source alternative would be great, I think it will take quite a dedicated developer to really bring this vision to life. 

There are also many moving parts with this proposal that I think testing the Aragon entity to manage a clone of Bitquest may offer an easy way to see how viable this idea will be in the long term. It could also show the power of Aragon. 

If you can get the economics down similar to how bitquest has (Vendors selling items to pool money for server events) then I think it could serve as a great way to slowly implement the same model on an open source alternative like Minetest if it proves successful. 

This would also be a lot lower overhead and upfront cost, in fact it may be self sustaining if you follow the bitquest model. If it gets popular, it may even become profitable in which case you could hire a dev to build out each component of your idea through micro bounties and through people involved in governance.

**Comment by DaniellMesquita** [comment]
> Ultimately, you'll have to work really hard to get some merit and get any respect back, and this is your loss, but it is also your job.
> 
> Until then, your idea is sunk, entirely, by your own undoing.

Yeah, the ideas of Aragon's Pando app is also sunk?
Then, reconsider the merits you said I don't have: Pando, with roadmap for 2019, was discontinued; even they being funded by Aragon. Boycott made by persons you probably know. As you username, you're @sofar from having respect and any merit, and simply by understanding and loving yourself.

https://github.com/pandonetwork/pando - Q3 2019
latest commit: 14 Jun 2019

> This software is still in beta stage and is not meant to be used in production yet. The testnet version is expected for Q2 2019. The mainnet version is expected for Q3 2019.

**Comment by DaniellMesquita** [comment]
> Ultimately, you'll have to work really hard to get some merit and get any respect back, and this is your loss, but it is also your job.
> 
> Until then, your idea is sunk, entirely, by your own undoing.

Yeah, the ideas of Aragon's Pando app is also sunk?
Then, reconsider the merits you said I don't have: Pando, with roadmap for 2019, was discontinued; even they being funded by Aragon. Boycott made by persons you probably know. As your username, you're @sofar from having respect and any merit, and simply by not understanding and loving yourself.

https://github.com/pandonetwork/pando - Q3 2019
latest commit: 14 Jun 2019

> This software is still in beta stage and is not meant to be used in production yet. The testnet version is expected for Q2 2019. The mainnet version is expected for Q3 2019.

**Comment by StephenLynx** [comment]
@DaniellMesquita jesus fucking christ, dude. Just fuck off.

**Comment by DaniellMesquita** [comment]
> jesus fucking christ, dude. Just fuck off.

You say about "unicorns" and "jesus" (both religious things) because you seem to not believe that yourself do exist.

I already explained you're wrong, obsessed in bullying people and trying to reply by last and feel yourself right and good by seeing the things bad and wrong.

As obvious, you all (you asked to say more the group you're supposedly part, but I won't play with your lawfare trap) say to the other what is only about yourselves. Don't do the gimmick workaround of making the people's suffering as a passing-life Netflix pseudo-prize. I don't need to say again for you to find a psychiatrist, or as they says, a therapy. Don't be nihilistic. Just try to love yourself. Be happy. Forget people who you want to see weak. Find your way.

> You are no more special than any other lolcow I mocked before.

Okay? Go find them, but altogether and send a print to a doctor.

And yeah, f@ck off:

![image](https://user-images.githubusercontent.com/6765277/73138037-f1f80480-403c-11ea-814c-0d90200f731a.png)

@Bradymck

> Also, for everyone else here. Tone down the insults. This really isn't helpful or in the spirit of how I see the Aragon community. If you don't like an idea move onto to something else.

That is.

> If you can get the economics down similar to how bitquest has (Vendors selling items to pool money for server events) then I think it could serve as a great way to slowly implement the same model on an open source alternative like Minetest if it proves successful.

My idea of real-value economy in games is now applied to Axie:
https://bitcode.substack.com/p/how-to-make-money-playing-blockchain

**Comment by StephenLynx** [comment]
@mariapao I would suggest a ban on this guy. Either he is incorrigible stupid or trolling.

**Comment by DaniellMesquita** [comment]
> I would suggest a ban on this guy. Either he is incorrigible stupid or trolling.

Saying before me what I didn't said; as I'm not a dictator or a supporter of so.

@mariapao

> Although what you propose is an interesting use case (open in-game economies, in general, are interesting to explore)

As all other serious developers stated on this issue. In-game economies are a great step towards against the corruptions of big enterprises and banks; I don't have fear to say that. And [Axie did it with excellence](https://axie.substack.com/p/axie-community-alpha-getting-started).

> If in the future you are working on something that is a fit for the program, please do not hesitate to apply again!

I'd proposed a issue about Open Badges and other fully describing a working education platform for Aragon, and it also received a development team interested in bringing it. It was refused.

> Education certainly is important, however, we are not approving this proposal at the moment. As mentioned in one of my comments to another of your proposals, this year the Nest program will be focused on funding teams building key Aragon infrastructure or applications.

Isn't just important. It is most important than Aragon Court and so important as Pando is. Education makes people aware (Brazil wouldn't like that), wise and self-corrigible.

> we are not approving this proposal as it is not aligned with the priorities of the Aragon project for 2019. This year the program will be mainly focused on funding teams building key Aragon infrastructure or applications.

Pando was considered a key Aragon application, with a roadmap for Q3 2019 and expensive funding, but was discontinued in prol of Fundraising app.

> Also, Nest will have a limited annual budget (that will be ratified by the ANT holders on Jan 24th) so we will be even more selective on what proposals to approve and projects to fund.

Limited budget which invested a lot in Pando for it being stuck. A education platform I'd proposed had a dedicated team willing to contribute on it. Yes, call me conspiracy theorist, but Freemasonry is throwing terror not only on Brazil, but in all places they can forget their mental confusion and ideological blindness.

**Comment by DaniellMesquita** [comment]
In regards of the mice-avatarized user, he is going to be included in the investigation about the hateful authoritarianism being spread in Brazil.

**Comment by StephenLynx** [comment]
Are you talking about me, @DaniellMesquita ? Because my avatar is the Cheshire cat. Either way, the "hateful authoritarianism being spread in Brazil" was hilarious. Do you defend mobsters posing as politicians too?

**Comment by StephenLynx** [comment]
And investigated by whom? The counter-illuminati? Take your damn meds.
>Yes, call me conspiracy theorist, but Freemasonry is throwing terror not only on Brazil, but in all places they can forget their mental confusion and ideological blindness.
Get professional help, my dude.
