### ISSUE TITLE
PanAragon Nest proposal

### ISSUE THREAD

**Issue by apeir99n** [aragon/nest#154]
# Request for Nest membership and funding

**Team name**: PanAragon

**Proof of concept / research whitepaper**: https://github.com/akropolisio/nest/blob/master/grants/PanAragon/PanAragon.md

**Burn rate**: $50k/month

**Legal structure**: Akropolis Decentralised Ltd. | Suite 23 Portland House, Glacis Road, Gibraltar, GX11 1AA | COMPANY NUMBER: 116430

**[Team and roadmap](1/files)** https://github.com/akropolisio/nest/blob/master/grants/PanAragon/team.md
https://github.com/akropolisio/nest/blob/master/grants/PanAragon/roadmap.md

## Proposal

Our team is committed to the improvement of Aragon Core by focusing on two major goals: gradual scalability towards a futuredelivery of the Arachain via R&D efforts based on Polkadot and Substrate, and network monetization strategies and  theimplementation of such. 

Our proposal, in a nutshell:
* Aragon Core technology development in collaboration with existing contributors/ flock teams where required; building tech tools for the Aragon ecosystem with a focus on scalability.
* Aragon Product Lab: Product-Market-Fit and Monetisation research 

[Read the Full Proposal →](https://github.com/akropolisio/nest/blob/master/grants/PanAragon/PanAragon.md)

**Comment by apeir99n** [comment]
This proposal has been adapted based on the feedback received by the Aragon Community, please read this version that focuses the scope on the most necessary features for Aragon Core and its scaling

**Comment by LouisGrx** [comment]
Hello PanAragon team, thanks for your patience waiting for feedback on your proposal for a Nest grant.

We highly appreciate that you considered the feedback that was provided when PanAragon applied to Flock during last AGP round. Unfortunately, there are multiple things we are not comfortable with and that have dissuaded us to approve this proposal. Let us detail the main points below.

### General remarks

#### Applying to Nest in order to apply to Flock in 3 months:
Thanks for sharing your intentions there. However, the path you suggest can be a bit worrying. Building a working L2 voting PoC on substrate integrating with a custom Oracle solution until the Next AGP process seems short in time (barely 3 months) if you don’t have an already clear idea on how to proceed. Building the Arachain promises to be difficult and it is (potentially) a critical piece of tech for Aragon. We don't want to rush its design. In the same regard, on-boarding a new Flock team is a special event where we want to make sure everything will run perfectly. Speed is not the focus on both of these matters.

#### Requirements:
Nest teams do not have such rights and these are Flock team only. 

### Feedback and remarks on the Nest proposal
Nest has evolved substantially in the past year, given the contraction in the market, we’ve only gotten $500k funded as the budget for the year 2019. We prefer to use this budget to fund working products and code that can be used by final users instead of research.

In your proposal a lot of attention is given to research and design, and we couldn’t really find much code anywhere to evaluate.

In the proposal there are a lot of different technologies mentioned (Oracles, substrate, state channels…) but the spec isn't particularly clear.

The Arachain will have to support much more than voting in the future and we need to have strong guarantees over the technical architecture, we can’t afford any risks on this one.
This is such a critical part of the infrastructure that we want to make sure it gets the proper attention and love it deserves. Delegating this task to a new team could prove itself not the best strategy as it would require a lot of time from Aragon One and other Flock teams in terms of onboarding and coordination. 

With all this being considered, we’re not going to go ahead with this proposal, but we really do appreciate the effort and thought that went into it.

Thanks a lot again for taking the time to apply. We’re available if you have questions.
