### ISSUE TITLE
Aragon Nest Proposal: Type safe Truffle alternative

### ISSUE THREAD

**Issue by moodysalem** [aragon/nest#27]
# Aragon Nest Proposal: Type safe Truffle alternative

## Abstract

Truffle is currently the best option for writing, testing, and deploying smart contracts. However the truffle lifecycle is synonymous with extendable build tool lifecycles like maven, and it's challenging to write smart contract tests in Javascript without the help of autocomplete or type safety. 

For the health of the ecosystem, build tool competition should exist in other languages. Maven has all the proper extension points to make writing smart contracts as simple as adding a few plugins, and Java is ideal for its type safety, maturity, and popularity with developers.

## Deliverables

1. A maven plugin that lets you author and compile solidity code in a maven project within the standard maven build lifecycle
2. The above plugin allows you to compile solidity referencing ethpm packages and solidity code sourced from GitHub/npm
3. A maven plugin that lets you run integration tests against an in-memory blockchain
4. A maven archetype that lets you initialize a smart contract repository from a template
5. A maven plugin to generate Java classes (possibly using web3j) as part of the build for test code autocompletion

## Grant size

TBD

## Application requirements

- Familiarity with the Java development ecosystem
- Experience developing and deploying smart contracts via Truffle to mainnet
- Understanding of maven and the maven build lifecycle

## Development timeline

The development timeline will be the following one in regards to each deliverable:

1. Apr 2018
2. Apr-May 2018
3. May 2018
4. June 2018
5. June 2018

**Comment by moodysalem** [comment]
Some feedback: it's a bit weird to specify grant size and development timeline for the project proposal-I'd think that should be specified by the developer requesting funding for the project

**Comment by mariapao** [comment]
@moodysalem Thanks a lot for the feedback! It can happen that people are already working on what they are proposing so they may have the numbers of the grant and the timeline a bit more clear than somebody that is just in the idea stage. Also, take into account that this is a guide so if people don't have an idea on the numbers and the timeline they can do what you just did regarding the grant size  and we can discuss those numbers and timeline once people submit the request for funding.

**Comment by mariapao** [comment]
Regarding the proposal, we agree with you: we need truffle alternatives. However, with this particular proposal we would like to take the initiative a bit. Internally, the dev team have started working on this with the idea of building an MVP and have the teams take it from there. We haven't been able to share anything on this regard (sorry!) because right now the team is focused on the launch. Once the launch is out of the way, we will make a proposal including the MVP, so please stay tuned! And last but not least, java is not in the list of languages at the moment.

I'm closing this proposal just for now and we will be posting a new one shortly!
